# config.yaml (LINUX EDITION)

# Default target range (Change this to match your lab)
default_subnet: "192.168.1.0/24"

nmap:
  # Standard Linux path for Nmap
  path: "/usr/bin/nmap"
  scripts: "vuln,vulners"

metasploit:
  host: "127.0.0.1"
  port: 55553
  user: "msf"
  password: "msf" 
  ssl: true

paths:
  scans: "data/scans"
  reports: "data/reports"